USE [JPCISCALEQA2025]
GO

/****** Object:  View [dbo].[JPCI_METADATA_INSIGHT_DIF_INCOMING_MESSAGE]    Script Date: 12/30/2025 9:14:49 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/*            
 Mod     | Programmer    | Date       | Modification Description            
 --------------------------------------------------------------------            
 JP1	 | Blake Becker  | 12/30/2025 | Added MESSAGE_TYPE and ROW.
*/

CREATE VIEW [dbo].[JPCI_METADATA_INSIGHT_DIF_INCOMING_MESSAGE]
AS 
SELECT DIM.MSG_ID
      ,DIM.ENCODING
      ,DIM.DATE_TIME_STAMP
      ,DIM.SOURCE_ID
      ,DIM.STATUS
      ,DIM.PROCESS_STAMP
      ,DIM.DATA
      ,DIM.USER_DEF1
      ,DIM.USER_DEF2
      ,DIM.USER_DEF3
      ,DIM.USER_DEF4
      ,DIM.USER_DEF5
      ,DIM.USER_DEF6
      ,DIM.USER_DEF7
      ,DIM.USER_DEF8
      ,DIM.USER_STAMP
      ,DIM.ENDPOINT_ID
      ,DIM.EVENT_ID
      ,DIM.MSG_PART1
      ,DIM.MSG_PART2
      ,DIM.MSG_PART3
      ,DIM.MSG_PART4
      ,DIM.MSG_PART5
      ,DIM.MSG_PART6
      ,DIM.MSG_PART7
      ,DIM.MSG_PART8
      ,DIM.MSG_PART9
      ,DIM.MSG_PART10
      ,DIM.MSG_PART11
      ,DIM.MSG_PART12
      ,DIM.MSG_PART13
      ,DIM.MSG_PART14
      ,DIM.MSG_PART15
      ,DIM.MSG_PART16
      ,DIM.MSG_PART17
      ,DIM.MSG_PART18
      ,DIM.MSG_PART19
      ,DIM.MSG_PART20
      ,DIM.MSG_PART21
      ,DIM.MSG_PART22
      ,DIM.MSG_PART23
      ,DIM.MSG_PART24
      ,DIM.MSG_PART25
      ,DIM.MSG_PART26
      ,DIM.MSG_PART27
      ,DIM.MSG_PART28
      ,DIM.MSG_PART29
      ,DIM.MSG_PART30
      ,dbo.RSCMfn_RtrvMsg(DIM.ERROR_MESSAGE) AS ERROR_MESSAGE
      ,DIM.INSERTED_DATE_TIME
      ,DIM.PROCESS_START_DATE_TIME
      ,DIM.PROCESS_END_DATE_TIME

      ,DEPT.NAME AS ENDPOINT_NAME
      ,DEPT.DESCRIPTION AS ENDPOINT_DESC
      ,DEPT.ENDPOINT_HANDLER
      ,DEPT.DIRECTION AS ENDPOINT_DIRECTION

      ,DE.EVENT_DESCRIPTION AS EVENT_DESC
      ,DE.ENABLED
      ,DE.EXECUTION_IDENTIFIER
      ,DE.MULTI_THREADED

      ,M.MESSAGE_TYPE -- Blake Becker 12/30/2025
      ,ROW_NUMBER() OVER (ORDER BY DIM.DATE_TIME_STAMP DESC) AS [ROW] -- Used to only show top 100 msgs (useful for ensuring messages are processing) Blake Becker 12/30/2025

  FROM DIF_INCOMING_MESSAGE DIM
  JOIN DIF_ENDPOINT DEPT
  on DIM.ENDPOINT_ID = DEPT.ENDPOINT_ID
  JOIN DIF_EVENT DE 
  on DIM.EVENT_ID = DE.EVENT_ID
  OUTER APPLY (SELECT J.[KEY] AS MESSAGE_TYPE FROM OPENJSON(DIM.DATA) J WHERE ISJSON(DIM.DATA) = 1) M -- Blake Becker 12/30/2025