SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
 Mod Number | Programmer    | Date       | Modification Description
 --------------------------------------------------------------------
 JP9        | Blake Becker  | 01/13/2026 | Created.

 This selects report header fields for SSRS report: ReceiptOverview
*/

CREATE OR ALTER PROCEDURE [dbo].[JP9_RPT_ReceiptOverviewHeader](@INTERNAL_RECEIPT_NUM NUMERIC(9)) AS

SET NOCOUNT ON;

--DECLARE @INTERNAL_RECEIPT_NUM NUMERIC(9) = 81068

DECLARE @TRAILER_ID NVARCHAR (25)
DECLARE @REC_DATE DATETIME

SELECT @TRAILER_ID = TRAILER_ID, @REC_DATE = ISNULL(RECEIPT_DATE, N'0')
FROM RECEIPT_HEADER WHERE INTERNAL_RECEIPT_NUM = @INTERNAL_RECEIPT_NUM

SELECT
	RH.TRAILER_ID
	,RH.RECEIPT_DATE
	,RECEIPT_ID = STRING_AGG(RH.RECEIPT_ID, ', ')
	,RECEIPT_TYPE = MIN(RH.RECEIPT_TYPE)
	,TOTAL_LINES = SUM(RH.TOTAL_LINES)
	,TOTAL_QTY = SUM(RH.TOTAL_QTY)
	,warehouse = MIN(RH.warehouse)
FROM
	RECEIPT_HEADER RH WITH (NOLOCK)
WHERE
	RH.TRAILER_ID = @TRAILER_ID
	AND RH.RECEIPT_DATE = @REC_DATE
GROUP BY
	RH.TRAILER_ID
	,RH.RECEIPT_DATE

GO
